## Posts
appad_blog_post:
    path:     /posts/
    defaults: { _controller: APPBlogBundle:Post:adminIndex }

appad_blog_post_create:
    path:     /posts/create/
    defaults: { _controller: APPBlogBundle:Post:adminCreate }

appad_blog_post_update:
    path:     /posts/update/{post}
    defaults: { _controller: APPBlogBundle:Post:adminUpdate }

appad_blog_post_delete:
    path:     /posts/delete/{post}
    defaults: { _controller: APPBlogBundle:Post:adminDelete }
