# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    #project.cacheimage_listener:
    #    class: WH\CmsBundle\Listener\CacheImageListener
    #    arguments: ["@liip_imagine.cache.manager"]
    #    tags:
    #        - { name: doctrine.event_listener, event: postUpdate }
    #        - { name: doctrine.event_listener, event: preRemove }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    fos_user.doctrine_registry:
        alias: doctrine


